### ISSUE TITLE
New version in appstore

### ISSUE THREAD

**Issue by sashagra** [gopa810/gcal-ios#1]
Hare Krishna. It was deleted from appstore.

**Comment by gopa810** [comment]
New version is available on app store under name "Gaudiya Calendar". 

Previous GCAL was renamed to "Gaudiya Calendar". 

Available on App Store now. 

On 2020-10-24 09:52, Alex wrote: 

> Hare Krishna. It was deleted from appstore. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].



Links:
------
[1] https://github.com/gopa810/gcal-ios/issues/1
[2]
